<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RememberMe</name>
   <tag></tag>
   <elementGuidId>bad1dab9-0338-403b-8737-aedef4837533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RememberMe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RememberMe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9ee8d05-e03c-4547-9e86-a0472c236cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d74d9668-0283-46b1-b77e-9d3d0b3a448a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f2a6b1a6-ea77-4d30-960a-8416299c6bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Remember me? field is required.</value>
      <webElementGuid>ce83b0dd-38d3-4e2d-94cd-6529c15ea834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RememberMe</value>
      <webElementGuid>90d7dfad-331c-42f9-b07f-016ba0529e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RememberMe</value>
      <webElementGuid>f7f8015d-4fa9-41e9-b851-a244b269529c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>74770a1a-9039-4818-b957-2326bb03556c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RememberMe&quot;)</value>
      <webElementGuid>4183f670-3f12-40c0-b67a-36e0e9b13666</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RememberMe']</value>
      <webElementGuid>4a94fae3-4b13-44d4-8702-7028c6984606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>e92a00fb-2e88-4f34-97df-116e140ef09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'RememberMe' and @name = 'RememberMe']</value>
      <webElementGuid>a9d19635-cfa9-45c4-bf09-5a3ac8ad2706</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
